# Generated by Django 5.2.8 on 2025-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_sale_delete_salesdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
